# Generated by Django 4.1.7 on 2023-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsection',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
