# Generated by Django 4.2.5 on 2023-10-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposalsection_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
