# Generated by Django 4.2.5 on 2023-10-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_saved_proposals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.userprofile'),
        ),
        migrations.AlterField(
            model_name='saved_proposals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.userprofile'),
        ),
    ]
