# Generated by Django 4.2.5 on 2023-10-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_rename_user_proposal_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved_proposals',
            old_name='user',
            new_name='username',
        ),
    ]
