# Generated by Django 4.2.5 on 2023-10-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_rename_user_saved_proposals_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsection',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.userprofile'),
        ),
    ]
